### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by JIzabal** [TylerLo416/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:
You have extra items in your list for the expected output of `testSnippet3`. You should only be collecting markdown links and not normal links. [The CommonMark demo site](https://spec.commonmark.org/dingus/) can help to see what output you should have, because it should only highlight markdown links.

Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by TylerLo416** [comment]
![snippet3-redo](https://user-images.githubusercontent.com/93793209/156999979-42b81fc1-dd80-423c-9e69-fb20db019248.PNG)

Is this the correct expected output of testSnippet3? I'm not sure if this is correct because it feels like the other links should work based on other tests I have done.

**Comment by TylerLo416** [comment]
@JIzabal ^ sorry if this is like rude to @ someone on github I just really need to finish this up early :)

**Comment by JIzabal** [comment]
No worries! That picture has the correct output (i.e., Your list would be `[https://ucsd-cse15l-w22.github.io/]`) . Only the CSE 15L website is highlighted, because it's the only markdown link (i.e., Uses `[]()` as the format correctly). Although the other links appear on the page, they appear normally instead of highlighting the text like it should be doing. For example, https://www.twitter.com should link from the text "this title text is really long and takes up more than one line and has some line breaks", however the line breaks cause the markdown link format to break. As a result, instead of appearing on the page as a markdown link, it just shows up as a regular link. Although on VS Code markdown preview https://www.twitter.com is highlighted, it's only highlighted because it's a link. If it were a markdown link, then it would just show the text "this title text is really long and takes up more than one line and has some line breaks" instead of https://www.twitter.com. Feel free to ask me any more questions!

**Comment by JIzabal** [comment]
Nice work!
